In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/raw/sample-superstore.csv',encoding='latin1')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

changing columns dtypes

In [6]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [7]:
df.duplicated().sum()

np.int64(0)

Feature engineering (creating columns )

In [38]:
df['month'] = df['order_date'].dt.month
df['year'] = df['order_date'].dt.year
df['month_name'] = df['order_date'].dt.month_name()

In [9]:
df['profit_margin'] = df['Profit'] /df['Sales']

In [10]:
df.columns=df.columns.str.lower()

In [11]:
df.columns

Index(['row id', 'order id', 'order date', 'ship date', 'ship mode',
       'customer id', 'customer name', 'segment', 'country', 'city', 'state',
       'postal code', 'region', 'product id', 'category', 'sub-category',
       'product name', 'sales', 'quantity', 'discount', 'profit', 'month',
       'year', 'month_name', 'profit_margin'],
      dtype='object')

In [12]:
df.columns = df.columns.str.replace(' ','_')

EDA

In [14]:
df.groupby('category')['profit'].sum().sort_values()

category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: profit, dtype: float64

creating a summary table to see desired data for good understanding 

comparing profit to sales to see how much profit we made (or better to create profit margin column)

In [15]:
summary = df.groupby('category')[['sales','profit']].sum()

In [16]:
summary['Profit_margin'] = summary['profit'] / summary['sales']

In [17]:
summary

                       sales       profit  Profit_margin
category
Furniture        741999.7953   18451.2728       0.024867
Office Supplies  719047.0320  122490.8008       0.170352
Technology       836154.0330  145454.9481       0.173957

Furniture category is not performing well ----- now lets see in that category which sub-categories are note perfoming well or all are not performing good.

In [18]:
df.groupby(['category','sub-category'])[['sales','profit']].sum()

                                    sales      profit
category        sub-category
Furniture       Bookcases     114879.9963  -3472.5560
                Chairs        328449.1030  26590.1663
                Furnishings    91705.1640  13059.1436
                Tables        206965.5320 -17725.4811
Office Supplies Appliances    107532.1610  18138.0054
                Art            27118.7920   6527.7870
                Binders       203412.7330  30221.7633
                Envelopes      16476.4020   6964.1767
                Fasteners       3024.2800    949.5182
                Labels         12486.3120   5546.2540
                Paper          78479.2060  34053.5693
                Storage       223843.6080  21278.8264
                Supplies       46673.5380  -1189.0995
Technology      Accessories   167380.3180  41936.6357
                Copiers       149528.0300  55617.8249
                Machines      189238.6310   3384.7569
                Phones        330007.0540  44515.7306

Now discount  vs profit  to see are losses happening in subcategory cuz of discounts

as discounts increases profit decreases becomes negative (loses)

====

In [19]:
df.groupby('discount')['profit'].mean().sort_index()

discount
0.00     66.900292
0.10     96.055074
0.15     27.288298
0.20     24.702572
0.30    -45.679636
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -101.796797
Name: profit, dtype: float64

Top products by sales

In [20]:
product_summary = df.groupby('product_name')[['sales','profit']].sum()

In [21]:
product_summary['profit_margin'] = product_summary['profit']/product_summary['sales']

In [ ]:

pd.options.display.float_format = '{:.2f}'.format

Region analysis

In [26]:
product_summary.sort_values('sales',ascending=False).head(10)

,sales,profit,profit_margin
product_name,,,
Canon imageCLASS 2200 Advanced Copier,61599.82,25199.93,0.41
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind,27453.38,7753.04,0.28
Cisco TelePresence System EX90 Videoconferencing Unit,22638.48,-1811.08,-0.08
HON 5400 Series Task Chairs for Big and Tall,21870.58,0.00,0.00
GBC DocuBind TL300 Electric Binding System,19823.48,2233.51,0.11
GBC Ibimaster 500 Manual ProClick Binding System,19024.50,760.98,0.04
Hewlett Packard LaserJet 3310 Copier,18839.69,6983.88,0.37
"HP Designjet T520 Inkjet Large Format Printer - 24"" Color",18374.90,4094.98,0.22
GBC DocuBind P400 Electric Binding System,17965.07,-1878.17,-0.10
High Speed Automatic Electric Letter Opener,17030.31,-262.00,-0.02

In [27]:
df.groupby('region')[['sales','profit']].sum()

            sales    profit
region
Central 501239.89  39706.36
East    678781.24  91522.78
South   391721.91  46749.43
West    725457.82 108418.45

In [28]:
region_summary = df.groupby('region')[['sales','profit']].sum()
region_summary['profit_margin'] = region_summary['profit']/region_summary['sales']
region_summary.sort_values('profit_margin',ascending=False)

            sales    profit  profit_margin
region
West    725457.82 108418.45           0.15
East    678781.24  91522.78           0.13
South   391721.91  46749.43           0.12
Central 501239.89  39706.36           0.08

Monthly trend

In [29]:
df.groupby(['year','month'])['sales'].sum()

year  month
2014  1        14236.90
      2         4519.89
      3        55691.01
      4        28295.35
      5        23648.29
      6        34595.13
      7        33946.39
      8        27909.47
      9        81777.35
      10       31453.39
      11       78628.72
      12       69545.62
2015  1        18174.08
      2        11951.41
      3        38726.25
      4        34195.21
      5        30131.69
      6        24797.29
      7        28765.33
      8        36898.33
      9        64595.92
      10       31404.92
      11       75972.56
      12       74919.52
2016  1        18542.49
      2        22978.81
      3        51715.88
      4        38750.04
      5        56987.73
      6        40344.53
      7        39261.96
      8        31115.37
      9        73410.02
      10       59687.75
      11       79411.97
      12       96999.04
2017  1        43971.37
      2        20301.13
      3        58872.35
      4        36521.54
      5        44261.11
      6        52981.73
      7        45264.42
      8        63120.89
      9        87866.65
      10       77776.92
      11      118447.82
      12       83829.32
Name: sales, dtype: float64

Phase 5 (final analysis for dashboard)

In [30]:
#top 10 products
df.groupby('product_name')[['sales','profit']].sum().sort_values(by='sales',ascending=False).head(10)

                                                      sales   profit
product_name
Canon imageCLASS 2200 Advanced Copier              61599.82 25199.93
Fellowes PB500 Electric Punch Plastic Comb Bind... 27453.38  7753.04
Cisco TelePresence System EX90 Videoconferencin... 22638.48 -1811.08
HON 5400 Series Task Chairs for Big and Tall       21870.58     0.00
GBC DocuBind TL300 Electric Binding System         19823.48  2233.51
GBC Ibimaster 500 Manual ProClick Binding System   19024.50   760.98
Hewlett Packard LaserJet 3310 Copier               18839.69  6983.88
HP Designjet T520 Inkjet Large Format Printer -... 18374.90  4094.98
GBC DocuBind P400 Electric Binding System          17965.07 -1878.17
High Speed Automatic Electric Letter Opener        17030.31  -262.00

In [31]:
pd.options.display.float_format='{:.2f}'.format

In [32]:
##region performance
df.groupby('region')[['sales','profit']].sum()

            sales    profit
region
Central 501239.89  39706.36
East    678781.24  91522.78
South   391721.91  46749.43
West    725457.82 108418.45

In [33]:
##monthly trend
df.groupby(['year','month'])['sales'].sum()

year  month
2014  1        14236.90
      2         4519.89
      3        55691.01
      4        28295.35
      5        23648.29
      6        34595.13
      7        33946.39
      8        27909.47
      9        81777.35
      10       31453.39
      11       78628.72
      12       69545.62
2015  1        18174.08
      2        11951.41
      3        38726.25
      4        34195.21
      5        30131.69
      6        24797.29
      7        28765.33
      8        36898.33
      9        64595.92
      10       31404.92
      11       75972.56
      12       74919.52
2016  1        18542.49
      2        22978.81
      3        51715.88
      4        38750.04
      5        56987.73
      6        40344.53
      7        39261.96
      8        31115.37
      9        73410.02
      10       59687.75
      11       79411.97
      12       96999.04
2017  1        43971.37
      2        20301.13
      3        58872.35
      4        36521.54
      5        44261.11
      6        52981.73
      7        45264.42
      8        63120.89
      9        87866.65
      10       77776.92
      11      118447.82
      12       83829.32
Name: sales, dtype: float64

In [34]:
#pivot table
pivot = df.pivot_table(
    values='sales',
    index='month',
    columns='year',
    aggfunc='sum'
)
pivot

year      2014     2015     2016      2017
month
1     14236.90 18174.08 18542.49  43971.37
2      4519.89 11951.41 22978.81  20301.13
3     55691.01 38726.25 51715.88  58872.35
4     28295.35 34195.21 38750.04  36521.54
5     23648.29 30131.69 56987.73  44261.11
6     34595.13 24797.29 40344.53  52981.73
7     33946.39 28765.33 39261.96  45264.42
8     27909.47 36898.33 31115.37  63120.89
9     81777.35 64595.92 73410.02  87866.65
10    31453.39 31404.92 59687.75  77776.92
11    78628.72 75972.56 79411.97 118447.82
12    69545.62 74919.52 96999.04  83829.32

In [40]:
df.to_csv('../data/cleaned/sample_superstore_cleaned.csv',index=False)

In [39]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sub-category,product_name,sales,quantity,discount,profit,month,year,month_name,profit_margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,11,2016,November,0.16
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,11,2016,November,0.30
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,6,2016,June,0.47
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03,10,2015,October,-0.40
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,10,2015,October,0.11